---

#This task installs and enables apache on webservers

- name: ensure apache is installed 
  apt: name=apache2 state=latest

- name: ensure apache is always running 
  service: name=apache2 state=running enabled=yes

- name: copy files to root 
  copy: src=image.png dest=/var/www/html/image.png

- name: copy application code to document root
  template: src=index.html.j2 dest=/var/www/html/index.html
  notify: restart apache
