---
- name: Configuring the ec2 instance 
  hosts: localhost
  connection: local
  tasks: 
  - name: Launching an ec2 instance
    ec2:
        key_name: "aman-key-pair"
        instance_type: "t2.micro"
        image: "ami-5e63d13e"
        wait: yes
        region: "us-west-2"
        user_data: "sudo apt-get install apache2 -y"
        group_id: "sg-66d0091d" 
        wait_timeout: 500
        vpc_subnet_id: "subnet-9766edce"
        volumes:
         - device_name: /dev/sdb
           volume_size: "8" 
           delete_on_termination: true
        monitoring: no
        assign_public_ip: yes
    register: ec2_data
  
  - name: Add the newly created EC2 instance(s) to the local host group (located inside the directory)
    lineinfile: 
        dest: "./hosts" 
        regexp: "{{ item.public_ip }}" 
        insertafter: "[webserver]"
        line: "{{ item.public_ip }}"
        with_items: "{{ ec2_data.instances }}" 

  #- name: Printing Public Ip of the above instance
  #  debug: 
  #      msg: "{{ ec2_data.public_ip }}"  

